name: 'Surefire Report'
description: 'Gather Surefire test results'
branding:
  icon: 'check-square'
  color: 'green'
inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  report_paths:
    description: 'surefire/failsafe/junit compatible xml report paths in glob format'
    required: false
    default: '**/surefire-reports/TEST-*.xml, **/failsafe-reports/TEST-*.xml'
  check_name:
    description: 'check name for test reports'
    required: false
    default: 'Test Report'
  commit:
    description: 'commit sha to update the status'
    required: false
  fail_on_test_failures:
    description: 'fail run if there were test failures'
    required: false
    default: 'false'
  fail_if_no_tests:
    description: 'fail run if there were no test results found'
    required: false
    default: 'true'
outputs:
  result:
     description: 'the test outcome, either `success` or `failure`'
  count:
     description: 'The number of tests included in the test'
  skipped:
     description: 'The number of skipped tests'
  failed:
     description: 'The number of failed tests'
  errorMessage:
     description: 'The error messages for failed tests'
runs:
  using: 'node12'
  main: 'dist/index.js'
